/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket_booking;

import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static java.util.Arrays.stream;

public class App {
    public static void main(String[] args) {

    }
}
